# Generated by Django 5.1.4 on 2025-01-02 02:54

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('title', models.CharField(max_length=200)),
                ('subtitle', models.CharField(blank=True, max_length=200, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('cover_image', models.ImageField(blank=True, default='', null=True, upload_to='')),
                ('id', models.UUIDField(default=uuid.UUID('7c59c8c3-5e96-4933-b9dc-e1f288a8350b'), editable=False, primary_key=True, serialize=False, unique=True)),
            ],
        ),
    ]
